import { chromium } from "playwright"
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
await page.goto("http://localhost:3000/login", { waitUntil: "networkidle" })
await page.fill("#email", "alex@example.com")
await page.fill("#password", "password123")
await page.getByRole("button", { name: /sign in/i }).click()
await page.waitForURL(/dashboard/, { timeout: 15000 })
await page.goto("http://localhost:3000/projects/cmt7je07g001das7z2tiph5sx", { waitUntil: "networkidle" })
await page.waitForTimeout(800)
await page.screenshot({ path: "/tmp/ui/14-project-fullpage.png", fullPage: true })
console.log("done")
await browser.close()
